### PR TITLE
[ELY-1686] Utility to port legacy properties files into a FileSystemRealm

### PR DESCRIPTION
**Pull request by justinmcook**
https://issues.jboss.org/browse/ELY-1686
https://issues.jboss.org/browse/EAP7-1093

Analysis Document: https://github.com/wildfly/wildfly-proposals/pull/136

Documentation PR: https://github.com/wildfly/wildfly/pull/11806

### CODE REVIEW

**Comment by justinmcook** [comment]
Still needs to be prechecked

**Comment by justinmcook** [comment]
Just updated this with some minor fixes, just to do with the --summary output and an issue with it not failing properly for invalid paths

**Comment by msve** [comment]
The feature was pre-checked, test coverage is part of this PR

**Comment by fjuma** [comment]
@justinmcook Just minor but please update the commits to reference the ELY issue. Thanks!

**Pull request merged**
